development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://fayeserv.herokuapp.com/faye"
  secret_token: "075cd5e4b513fc0eed9f7d13ffab227e73fb54a97e9c688fb55d3991549b9d31"
  signature_expiration: 3600 # one hour
